# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaymentDemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaymentDemoApp
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Alamofire', '~> 4.5'
  pod 'CardIO'
  

  target 'PaymentDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaymentDemoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
